# Generated by Django 5.0.6 on 2025-04-07 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now)),
                ('hora_recepcion', models.TimeField(default=django.utils.timezone.now)),
                ('entidad_emite', models.CharField(max_length=255)),
                ('numero_cedula_expediente', models.CharField(max_length=255)),
                ('dirigido_a', models.CharField(max_length=255)),
                ('recepcionista', models.CharField(choices=[('Amanda González', 'Amanda González'), ('Wanda Pastor', 'Wanda Pastor')], max_length=255)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifreception.colaborador')),
            ],
        ),
    ]
