# Generated by Django 5.0.6 on 2025-04-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifreception', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='colaborador_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
