# Generated by Django 5.0.6 on 2025-04-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifreception', '0002_remove_notificacion_colaborador_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
