# Generated by Django 5.0.6 on 2025-04-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifreception', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liquidation',
        ),
    ]
