# Generated by Django 5.0.6 on 2025-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifreception', '0005_delete_liquidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField()),
                ('received_time', models.TimeField()),
                ('issuing_entity', models.CharField(max_length=255)),
                ('case_number', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('receptionist', models.CharField(max_length=255)),
                ('internal_delivery_time', models.TimeField()),
                ('internal_collaborator', models.CharField(max_length=255)),
                ('final_delivery_datetime', models.DateTimeField()),
            ],
        ),
    ]
